"""El archivo de nombre “tarea6.1.py”, presenta las tablas de verdad and y or con tres operandos, la
tarea consiste en escribir las tablas de verdad nand y nor. Siendo nand (not and) la negación del
operador lógico and, y nor (not or) la negación del operador lógico or."""
print("Tabla de verdad del operador lógico and")
print()
print("False and False and False =", False and False and False)
print("False and False and True =", False and False and True)
print("False and True and False =", False and True and False)
print("False and True and True =", False and True and True)
print("True and False and False =", True and False and False)
print("True and False and True =", True and False and True)
print("True and True and False =", True and True and False)
print("True and True and True =", True and True and True)
print()
print("Tabla de verdad del operador lógico or")
print()
print("False or False or False =", False or False or False)
print("False or False or True =", False or False or True)
print("False or True or False =", False or True or False)
print("False or True or True =", False or True or True)
print("True or False or False =", True or False or False)
print("True or False or True =", True or False or True)
print("True or True or False =", True or True or False)
print("True or True or True =", True or True or True)
print()
# Escribir la tabla de verdad nand (not and)
print("Tabla de verdad nand")
print()

# Escribir la tabla de verdad nor (not or)
print("Tabla de verdad nor")
print()
